### ISSUE TITLE
 Failure to Launch: wrong version is present

### ISSUE THREAD

**Issue by ClaudiusMinimus** [agorasim20/ApplesCarrots#1]
Tried to test Apples & Carrots for the 1.18 Snapshot, but failed to launch.

Minecraft Snapshot: 21w3a (1.18 alpha)
apples-carrots-1.1 (shown as 1.18 compatible on CF)
fabric-api-0.41.3+1.18

`Mod 'DefaultSettings' (defaultsettings) requires "any 1.17.x version" of 'Minecraft' (minecraft), but only the wrong version is present: 1.18-alpha.21.43.a!`
https://pastebin.com/UxrVY3Jq

**Comment by agorasim20** [comment]
Looks like "fabric.mod.json" is outdated. Officially there is not version for 21w43a but if you want to build it, you need to change "minecraft" version in "depends" to minecraft: "1.18.x"

**Comment by agorasim20** [comment]
Or I could do it and upload a 21w43a version if you want, just give me a couple of minutes!

**Comment by agorasim20** [comment]
All right, I uploaded a 21w43a version to CurseForge. Just change what I said and then genSources and build.
You can find this new version in: https://www.curseforge.com/minecraft/mc-mods/apples-carrots/files

**Comment by ClaudiusMinimus** [comment]
Thank! It loaded fine and tested all of the apples and they worked great! I hope to publish a Fabric Edition of my 99 Mods on the Wall pack this week - your mod will be part of it.

Thanks again,
CM
